//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: result/dataconfig_gameparamsconfig_conf.proto
namespace dataconfig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAMEPARAMSCONFIG_CONF")]
  public partial class GAMEPARAMSCONFIG_CONF : global::ProtoBuf.IExtensible
  {
    public GAMEPARAMSCONFIG_CONF() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _food_density;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"food_density", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float food_density
    {
      get { return _food_density; }
      set { _food_density = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _foods_socre_def = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"foods_socre_def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> foods_socre_def
    {
      get { return _foods_socre_def; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAMEPARAMSCONFIG_CONF_ARRAY")]
  public partial class GAMEPARAMSCONFIG_CONF_ARRAY : global::ProtoBuf.IExtensible
  {
    public GAMEPARAMSCONFIG_CONF_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<dataconfig.GAMEPARAMSCONFIG_CONF> _items = new global::System.Collections.Generic.List<dataconfig.GAMEPARAMSCONFIG_CONF>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dataconfig.GAMEPARAMSCONFIG_CONF> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}